# Generated by Django 5.2.13 on 2026-04-26 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("core", "0001_initial"),
        ("produtos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(blank=True, db_index=True, max_length=30)),
                ("data_compra", models.DateTimeField(auto_now_add=True)),
                ("data_entrega", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "frete",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("forma_pagamento", models.CharField(blank=True, max_length=30)),
                ("parcelas", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cotacao", "Cotacao"),
                            ("pedido", "Pedido"),
                            ("recebida", "Recebida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pedido",
                        max_length=15,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("nfe_chave", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras",
                        to="core.empresa",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.fornecedor",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Compras",
                "ordering": ["-data_compra"],
            },
        ),
        migrations.CreateModel(
            name="CompraItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="compras.compra",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produtos.produto",
                    ),
                ),
            ],
        ),
    ]
