# Generated by Django 5.2.13 on 2026-04-26 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegracaoMercadoLivre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ml_user_id",
                    models.CharField(max_length=50, verbose_name="User ID ML"),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_expira", models.DateTimeField()),
                ("nickname", models.CharField(blank=True, max_length=100)),
                ("ativa", models.BooleanField(default=True)),
                ("ultima_sincronizacao", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_integracao",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integracao Mercado Livre",
                "verbose_name_plural": "Integracoes Mercado Livre",
            },
        ),
        migrations.CreateModel(
            name="PlataformaIntegracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plataforma",
                    models.CharField(
                        choices=[
                            ("mercadolivre", "Mercado Livre"),
                            ("shopee", "Shopee"),
                            ("magazineluiza", "Magazine Luiza"),
                            ("amazon", "Amazon"),
                            ("americanas", "Americanas"),
                            ("maxdata", "Maxdata (Importacao)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ativa", models.BooleanField(default=False)),
                ("configuracao", models.JSONField(blank=True, default=dict)),
                ("ultima_sincronizacao", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integracoes",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plataforma de Integracao",
                "verbose_name_plural": "Plataformas de Integracao",
                "unique_together": {("empresa", "plataforma")},
            },
        ),
        migrations.CreateModel(
            name="LogSincronizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("produtos", "Produtos"),
                            ("pedidos", "Pedidos"),
                            ("estoque", "Estoque"),
                            ("precos", "Precos"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sucesso", "Sucesso"),
                            ("erro", "Erro"),
                            ("parcial", "Parcial"),
                        ],
                        max_length=10,
                    ),
                ),
                ("registros_processados", models.IntegerField(default=0)),
                ("registros_erro", models.IntegerField(default=0)),
                ("detalhes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="integracao.plataformaintegracao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Sincronizacao",
                "verbose_name_plural": "Logs de Sincronizacao",
                "ordering": ["-created_at"],
            },
        ),
    ]
