# Generated by Django 5.2.13 on 2026-04-26 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razao_social", models.CharField(max_length=200)),
                ("nome_fantasia", models.CharField(max_length=200)),
                ("cnpj", models.CharField(max_length=20, unique=True)),
                ("inscricao_estadual", models.CharField(blank=True, max_length=30)),
                ("endereco", models.CharField(blank=True, max_length=300)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(default="GO", max_length=2)),
                ("cep", models.CharField(blank=True, max_length=10)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("atacado", "Atacado"),
                            ("varejo", "Varejo"),
                            ("ambos", "Atacado & Varejo"),
                        ],
                        default="ambos",
                        max_length=10,
                    ),
                ),
                ("ativa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Empresas",
                "ordering": ["nome_fantasia"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perfil",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("gerente", "Gerente"),
                            ("vendedor", "Vendedor"),
                            ("caixa", "Caixa"),
                            ("estoquista", "Estoquista"),
                        ],
                        default="vendedor",
                        max_length=20,
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20)),
                (
                    "empresa_padrao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios_padrao",
                        to="core.empresa",
                    ),
                ),
                (
                    "empresas",
                    models.ManyToManyField(related_name="usuarios", to="core.empresa"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfis de Usuarios",
            },
        ),
    ]
