# Generated by Django 5.2.13 on 2026-04-26 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("produtos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentacaoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("saida", "Saida"),
                            ("ajuste", "Ajuste"),
                            ("transferencia", "Transferencia"),
                            ("devolucao", "Devolucao"),
                        ],
                        max_length=15,
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "quantidade_anterior",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "quantidade_posterior",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "custo_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("documento_tipo", models.CharField(blank=True, max_length=20)),
                ("documento_id", models.IntegerField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="produtos.produto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentacao de Estoque",
                "verbose_name_plural": "Movimentacoes de Estoque",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Estoques",
                "unique_together": {("empresa", "produto")},
            },
        ),
    ]
