# Generated by Django 5.2.13 on 2026-04-26 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("compras", "0001_initial"),
        ("core", "0001_initial"),
        ("vendas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaPagar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("categoria", models.CharField(blank=True, max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_emissao", models.DateField()),
                ("data_vencimento", models.DateField()),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                (
                    "valor_pago",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "juros",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "multa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("forma_pagamento", models.CharField(blank=True, max_length=30)),
                ("documento", models.CharField(blank=True, max_length=50)),
                ("parcela", models.IntegerField(default=1)),
                ("total_parcelas", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("paga", "Paga"),
                            ("vencida", "Vencida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="compras.compra",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contas_pagar",
                        to="core.empresa",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta a Pagar",
                "verbose_name_plural": "Contas a Pagar",
                "ordering": ["data_vencimento"],
            },
        ),
        migrations.CreateModel(
            name="ContaReceber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("categoria", models.CharField(blank=True, max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_emissao", models.DateField()),
                ("data_vencimento", models.DateField()),
                ("data_recebimento", models.DateField(blank=True, null=True)),
                (
                    "valor_recebido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "juros",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "multa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("forma_pagamento", models.CharField(blank=True, max_length=30)),
                ("documento", models.CharField(blank=True, max_length=50)),
                ("parcela", models.IntegerField(default=1)),
                ("total_parcelas", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("recebida", "Recebida"),
                            ("vencida", "Vencida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contas_receber",
                        to="core.empresa",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vendas.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta a Receber",
                "verbose_name_plural": "Contas a Receber",
                "ordering": ["data_vencimento"],
            },
        ),
        migrations.CreateModel(
            name="FluxoCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saida")],
                        max_length=10,
                    ),
                ),
                ("categoria", models.CharField(blank=True, max_length=100)),
                ("descricao", models.CharField(max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_movimento", models.DateField()),
                ("forma_pagamento", models.CharField(blank=True, max_length=30)),
                ("documento_tipo", models.CharField(blank=True, max_length=20)),
                ("documento_id", models.IntegerField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fluxo de Caixa",
                "verbose_name_plural": "Fluxo de Caixa",
                "ordering": ["-data_movimento"],
            },
        ),
    ]
