# Generated by Django 5.2.13 on 2026-04-26 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("core", "0001_initial"),
        ("produtos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(blank=True, db_index=True, max_length=30)),
                ("data_venda", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("varejo", "Varejo"), ("atacado", "Atacado")],
                        default="varejo",
                        max_length=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "desconto_percentual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "desconto_valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "acrescimo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("pix", "PIX"),
                            ("cartao_debito", "Cartao Debito"),
                            ("cartao_credito", "Cartao Credito"),
                            ("boleto", "Boleto"),
                            ("prazo", "A Prazo"),
                            ("cheque", "Cheque"),
                        ],
                        default="dinheiro",
                        max_length=20,
                    ),
                ),
                ("parcelas", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                            ("devolvida", "Devolvida"),
                        ],
                        default="aberta",
                        max_length=15,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("nfe_numero", models.CharField(blank=True, max_length=50)),
                ("nfe_status", models.CharField(blank=True, max_length=30)),
                (
                    "ml_order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="ID Pedido ML",
                    ),
                ),
                (
                    "ml_pack_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ID Pack ML"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendas",
                        to="core.empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vendas",
                "ordering": ["-data_venda"],
            },
        ),
        migrations.CreateModel(
            name="Comissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("percentual", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("paga", "Paga"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("data_pagamento", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comissoes",
                        to="clientes.vendedor",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comissoes",
                        to="vendas.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comissao",
                "verbose_name_plural": "Comissoes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "comissao_percentual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "comissao_valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produtos.produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="vendas.venda",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="venda",
            index=models.Index(
                fields=["empresa", "status"], name="vendas_vend_empresa_79a57e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venda",
            index=models.Index(
                fields=["empresa", "data_venda"], name="vendas_vend_empresa_08067c_idx"
            ),
        ),
    ]
