# Generated by Django 5.2.13 on 2026-04-26 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigla", models.CharField(max_length=5, unique=True)),
                ("descricao", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["sigla"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("ativa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50)),
                (
                    "codigo_barras",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                (
                    "ncm",
                    models.CharField(blank=True, max_length=10, verbose_name="NCM"),
                ),
                (
                    "cfop_venda",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="CFOP Venda"
                    ),
                ),
                (
                    "preco_custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "preco_venda",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "preco_atacado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "margem_lucro",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "estoque_minimo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estoque_maximo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("localizacao", models.CharField(blank=True, max_length=50)),
                (
                    "peso",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="produtos/"),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "ml_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="ID Mercado Livre",
                    ),
                ),
                ("ml_permalink", models.URLField(blank=True, verbose_name="Link ML")),
                (
                    "ml_sync",
                    models.BooleanField(default=False, verbose_name="Sincronizar ML"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produtos.categoria",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="core.empresa",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produtos.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Produtos",
                "ordering": ["nome"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "codigo"],
                        name="produtos_pr_empresa_a6366a_idx",
                    ),
                    models.Index(
                        fields=["empresa", "ativo"],
                        name="produtos_pr_empresa_830dc7_idx",
                    ),
                ],
            },
        ),
    ]
